# Generated by Django 3.1.3 on 2020-12-18 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(blank=True, verbose_name='Away game appearences')),
                ('minutes_played', models.IntegerField(blank=True, verbose_name='Away minutes played')),
                ('goals_scored', models.IntegerField(blank=True, verbose_name='Away goals scored')),
                ('assists', models.IntegerField(blank=True, verbose_name='Away assists')),
                ('yellow_cards', models.IntegerField(blank=True, verbose_name='Away yellow cards')),
                ('red_cards', models.IntegerField(blank=True, verbose_name='Away red cards')),
                ('shots_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Away shots per game')),
                ('pass_success_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away pass success percentage')),
                ('aerials_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away aerials won')),
                ('man_of_the_match', models.IntegerField(blank=True, verbose_name='Away man of the match')),
                ('away_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(blank=True, verbose_name='Home game appearences')),
                ('minutes_played', models.IntegerField(blank=True, verbose_name='Home minutes played')),
                ('goals_scored', models.IntegerField(blank=True, verbose_name='Home goals scored')),
                ('assists', models.IntegerField(blank=True, verbose_name='Home assists')),
                ('yellow_cards', models.IntegerField(blank=True, verbose_name='Home yellow cards')),
                ('red_cards', models.IntegerField(blank=True, verbose_name='Home red cards')),
                ('shots_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Home shots per game')),
                ('pass_success_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home pass success percentage')),
                ('aerials_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home aerials won')),
                ('man_of_the_match', models.IntegerField(blank=True, verbose_name='Home man of the match')),
                ('away_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('league', models.CharField(choices=[('Premier League', 'Premier League'), ('Serie A', 'Serie A'), ('LaLiga', 'LaLiga'), ('BundesLiga', 'BundesLiga'), ('Ligue 1', 'Ligue 1')], max_length=100, verbose_name='League')),
                ('shirt_number', models.IntegerField(blank=True, verbose_name='Shirt Number')),
                ('height', models.IntegerField(blank=True, verbose_name='Height in CM')),
                ('positions', models.CharField(blank=True, max_length=256, verbose_name='Positions')),
                ('current_team', models.CharField(blank=True, max_length=100, verbose_name='Current Team')),
                ('date_of_birth', models.DateField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('away_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.awaystats')),
                ('home_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.homestats')),
            ],
        ),
    ]
