# Generated by Django 3.1.3 on 2021-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('fullname', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('shortname', models.CharField(blank=True, max_length=100, verbose_name='Short Name')),
                ('founded', models.DateField(blank=True)),
                ('ground', models.CharField(blank=True, max_length=100, verbose_name='Ground')),
                ('ground_capacity', models.IntegerField(blank=True, verbose_name='Ground Capacity')),
            ],
        ),
    ]
