# Generated by Django 3.1.3 on 2020-11-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaystats',
            name='aerials_won',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away aerials won'),
        ),
        migrations.AddField(
            model_name='awaystats',
            name='away_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away rating'),
        ),
        migrations.AddField(
            model_name='awaystats',
            name='pass_success_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Away pass success percentage'),
        ),
    ]
