# Generated by Django 3.1.3 on 2020-11-21 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201117_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(blank=True, verbose_name='Home game appearences')),
                ('minutes_played', models.IntegerField(blank=True, verbose_name='Home minutes played')),
                ('goals_scored', models.IntegerField(blank=True, verbose_name='Home goals scored')),
                ('assists', models.IntegerField(blank=True, verbose_name='Home assists')),
                ('yellow_cards', models.IntegerField(blank=True, verbose_name='Home yellow cards')),
                ('red_cards', models.IntegerField(blank=True, verbose_name='Home red cards')),
                ('shots_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Home shots per game')),
                ('pass_success_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home pass success percentage')),
                ('aerials_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home aerials won')),
                ('man_of_the_match', models.IntegerField(blank=True, verbose_name='Home man of the match')),
                ('away_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Home rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
