# Generated by Django 3.1.3 on 2021-01-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='League Name')),
                ('organising_body', models.CharField(blank=True, max_length=100, verbose_name='Organising Body')),
                ('founded', models.DateField()),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('confederation', models.CharField(blank=True, max_length=100, verbose_name='Confederation')),
                ('no_of_teams', models.IntegerField(blank=True, verbose_name='Number of Teams')),
            ],
        ),
        migrations.RemoveField(
            model_name='awaystats',
            name='game_appearences',
        ),
        migrations.RemoveField(
            model_name='homestats',
            name='game_appearences',
        ),
        migrations.AddField(
            model_name='awaystats',
            name='game_appearances',
            field=models.IntegerField(blank=True, default=0, verbose_name='Away game appearances'),
        ),
        migrations.AddField(
            model_name='homestats',
            name='game_appearances',
            field=models.IntegerField(blank=True, default=0, verbose_name='Home game appearances'),
        ),
        migrations.AddField(
            model_name='team',
            name='head_coach',
            field=models.CharField(blank=True, max_length=100, verbose_name='Head Coach'),
        ),
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nick Name'),
        ),
        migrations.AddField(
            model_name='team',
            name='president',
            field=models.CharField(blank=True, max_length=100, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.league'),
            preserve_default=False,
        ),
    ]
