# Generated by Django 3.1.3 on 2021-01-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.team')),
                ('association', models.CharField(blank=True, max_length=100, verbose_name='Association')),
                ('confederation', models.CharField(blank=True, max_length=100, verbose_name='confederation')),
                ('fifa_code', models.CharField(blank=True, max_length=100, verbose_name='Fifa Code')),
                ('captain', models.CharField(blank=True, max_length=100, verbose_name='Captain')),
            ],
            bases=('core.team',),
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='president',
        ),
        migrations.AddField(
            model_name='player',
            name='national_team',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nationalteam'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.team')),
                ('founded', models.DateField(blank=True)),
                ('president', models.CharField(blank=True, max_length=100, verbose_name='President')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
            ],
            bases=('core.team',),
        ),
        migrations.AddField(
            model_name='player',
            name='league_team',
            field=models.ManyToManyField(blank=True, to='core.LeagueTeam'),
        ),
    ]
