# Generated by Django 3.1.3 on 2020-11-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Home game appearences')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('league', models.CharField(choices=[('Premier League', 'Premier League'), ('Serie A', 'Serie A'), ('LaLiga', 'LaLiga'), ('BundesLiga', 'BundesLiga'), ('Ligue 1', 'Ligue 1')], max_length=100, verbose_name='League')),
                ('shirt_number', models.IntegerField(blank=True, verbose_name='Shirt Number')),
                ('height', models.IntegerField(blank=True, verbose_name='Height in CM')),
                ('positions', models.CharField(blank=True, max_length=256, verbose_name='Positions')),
                ('current_team', models.CharField(blank=True, max_length=100, verbose_name='Current Team')),
                ('date_of_birth', models.DateField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('away_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.awaystats')),
                ('home_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homestats')),
            ],
        ),
    ]
