# Generated by Django 3.1.3 on 2021-02-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210130_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamA', to='core.leagueteam')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamB', to='core.leagueteam')),
            ],
        ),
    ]
