# Generated by Django 3.1.3 on 2020-11-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='away_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.awaystats'),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.homestats'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Player Name'),
        ),
    ]
