# Generated by Django 3.1.7 on 2021-03-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210213_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='away_stats',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.awaystats'),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_stats',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.homestats'),
        ),
    ]
