# Generated by Django 3.1.7 on 2021-03-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210310_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='national_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nationalteam'),
        ),
    ]
